<?php

namespace Proxies\__CG__\GSB\VisiteurBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Visiteur extends \GSB\VisiteurBundle\Entity\Visiteur implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'GSB\\VisiteurBundle\\Entity\\Visiteur' . "\0" . 'id', '' . "\0" . 'GSB\\VisiteurBundle\\Entity\\Visiteur' . "\0" . 'loginVis', '' . "\0" . 'GSB\\VisiteurBundle\\Entity\\Visiteur' . "\0" . 'mdpVis', '' . "\0" . 'GSB\\VisiteurBundle\\Entity\\Visiteur' . "\0" . 'nomVis', '' . "\0" . 'GSB\\VisiteurBundle\\Entity\\Visiteur' . "\0" . 'prenomVis', '' . "\0" . 'GSB\\VisiteurBundle\\Entity\\Visiteur' . "\0" . 'adresseVis', '' . "\0" . 'GSB\\VisiteurBundle\\Entity\\Visiteur' . "\0" . 'cpVis', '' . "\0" . 'GSB\\VisiteurBundle\\Entity\\Visiteur' . "\0" . 'villeVis', '' . "\0" . 'GSB\\VisiteurBundle\\Entity\\Visiteur' . "\0" . 'dateEmbaucheVis'];
        }

        return ['__isInitialized__', '' . "\0" . 'GSB\\VisiteurBundle\\Entity\\Visiteur' . "\0" . 'id', '' . "\0" . 'GSB\\VisiteurBundle\\Entity\\Visiteur' . "\0" . 'loginVis', '' . "\0" . 'GSB\\VisiteurBundle\\Entity\\Visiteur' . "\0" . 'mdpVis', '' . "\0" . 'GSB\\VisiteurBundle\\Entity\\Visiteur' . "\0" . 'nomVis', '' . "\0" . 'GSB\\VisiteurBundle\\Entity\\Visiteur' . "\0" . 'prenomVis', '' . "\0" . 'GSB\\VisiteurBundle\\Entity\\Visiteur' . "\0" . 'adresseVis', '' . "\0" . 'GSB\\VisiteurBundle\\Entity\\Visiteur' . "\0" . 'cpVis', '' . "\0" . 'GSB\\VisiteurBundle\\Entity\\Visiteur' . "\0" . 'villeVis', '' . "\0" . 'GSB\\VisiteurBundle\\Entity\\Visiteur' . "\0" . 'dateEmbaucheVis'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Visiteur $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setLoginVis($loginVis)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLoginVis', [$loginVis]);

        return parent::setLoginVis($loginVis);
    }

    /**
     * {@inheritDoc}
     */
    public function getLoginVis()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLoginVis', []);

        return parent::getLoginVis();
    }

    /**
     * {@inheritDoc}
     */
    public function setMdpVis($mdpVis)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMdpVis', [$mdpVis]);

        return parent::setMdpVis($mdpVis);
    }

    /**
     * {@inheritDoc}
     */
    public function getMdpVis()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMdpVis', []);

        return parent::getMdpVis();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomVis($nomVis)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomVis', [$nomVis]);

        return parent::setNomVis($nomVis);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomVis()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomVis', []);

        return parent::getNomVis();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrenomVis($prenomVis)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrenomVis', [$prenomVis]);

        return parent::setPrenomVis($prenomVis);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrenomVis()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrenomVis', []);

        return parent::getPrenomVis();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdresseVis($adresseVis)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdresseVis', [$adresseVis]);

        return parent::setAdresseVis($adresseVis);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdresseVis()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdresseVis', []);

        return parent::getAdresseVis();
    }

    /**
     * {@inheritDoc}
     */
    public function setCpVis($cpVis)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCpVis', [$cpVis]);

        return parent::setCpVis($cpVis);
    }

    /**
     * {@inheritDoc}
     */
    public function getCpVis()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCpVis', []);

        return parent::getCpVis();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateEmbaucheVis($dateEmbaucheVis)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateEmbaucheVis', [$dateEmbaucheVis]);

        return parent::setDateEmbaucheVis($dateEmbaucheVis);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateEmbaucheVis()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateEmbaucheVis', []);

        return parent::getDateEmbaucheVis();
    }

    /**
     * {@inheritDoc}
     */
    public function setVilleVis($villeVis)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVilleVis', [$villeVis]);

        return parent::setVilleVis($villeVis);
    }

    /**
     * {@inheritDoc}
     */
    public function getVilleVis()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVilleVis', []);

        return parent::getVilleVis();
    }

}
