<?php

namespace GSB\VisiteurBundle\Repository;

/**
 * EtatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtatRepository extends \Doctrine\ORM\EntityRepository
{
	public function lEtat(){
	$id = 'CR';
	$queryBuilder = $this->_em->createQueryBuilder('v');

	$queryBuilder
		->select('e')
		->from('GSBVisiteurBundle:Etat','e')
		->where('e.id = :id')
		->setParameter('id',$id);

	return $queryBuilder->getQuery()->getSingleResult();
	}
    
}
