<?php

namespace GSB\VisiteurBundle\Repository;

/**
 * LigneFraisForfaitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LigneFraisForfaitRepository extends \Doctrine\ORM\EntityRepository
{
	public function getLff($id,$mois){
		$queryBuilder = $this->_em->createQueryBuilder('lff');
		
		$queryBuilder
		        ->select('lff.id','lff.quantiteLff','frais.libelleFrais','frais.montantFrais')
		        ->from('GSBVisiteurBundle:LigneFraisForfait','lff')
			->innerJoin('GSBVisiteurBundle:FraisForfait','frais')
			->where('lff.idFrais = frais.id')
			->andWhere('lff.idVis =:id')
			->andWhere('lff.moisFf =:mois')
			->setParameter('id', $id)
			->setParameter('mois', $mois);
		return $queryBuilder->getQuery()->getArrayResult();
	}

	public function getMontantValide($id,$mois){
		$queryBuilder = $this->_em->createQueryBuilder('lff');
		
		$queryBuilder
		        ->select('lff.quantiteLff','frais.libelleFrais','frais.montantFrais')
		        ->from('GSBVisiteurBundle:LigneFraisForfait','lff')
			->innerJoin('GSBVisiteurBundle:FraisForfait','frais')
			->where('lff.idFrais = frais.id')
			->andWhere('lff.idVis =:id')
			->andWhere('lff.moisFf =:mois')
			->setParameter('id', $id)
			->setParameter('mois', $mois);
		return $queryBuilder->getQuery()->getArrayResult();
	}

	public function supprimerLff($id,$mois,$idLff){
		$query = $this->_em->createQuery("delete GSBVisiteurBundle:LigneFraisForfait lff  
					where lff.idVis = ".$id." 
					and lff.moisFf = ".$mois."
					and lff.id = ".$idLff);
		$query->execute();
	}

}


