<?php

namespace GSB\VisiteurBundle\Repository;

/**
 * LigneFraisHorsForfaitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LigneFraisHorsForfaitRepository extends \Doctrine\ORM\EntityRepository
{
	public function getLfhf($id,$mois){
		$queryBuilder = $this->_em->createQueryBuilder('lfhf');
		
		$queryBuilder
		        ->select('lfhf')
		        ->from('GSBVisiteurBundle:LigneFraisHorsForfait','lfhf')
			->where('lfhf.idVis =:id')
			->andWhere('lfhf.moisFf =:mois')
			->setParameter('id', $id)
			->setParameter('mois', $mois);
		return $queryBuilder->getQuery()->getArrayResult();
	}

	public function getNbJFf($id,$mois){
		$queryBuilder = $this->_em->createQueryBuilder('lfhf');
		
		$queryBuilder
		        ->select('count(lfhf.id)')
		        ->from('GSBVisiteurBundle:LigneFraisHorsForfait','lfhf')
			->where('lfhf.idVis =:id')
			->andWhere('lfhf.moisFf =:mois')
			->setParameter('id', $id)
			->setParameter('mois', $mois);
		return $queryBuilder->getQuery()->getSingleResult();
	}
	
	public function supprimerLfhf($id,$mois,$idLfhf){
		$query = $this->_em->createQuery("delete GSBVisiteurBundle:LigneFraisHorsForfait lfhf  
					where lfhf.idVis = ".$id." 
					and lfhf.moisFf = ".$mois."
					and lfhf.id = ".$idLfhf);
		$query->execute();
	}
}
