<?php

namespace GSB\VisiteurBundle\Repository;

/**
 * VisiteurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VisiteurRepository extends \Doctrine\ORM\EntityRepository
{

	public function trouverVis($login,$mdp){
	$queryBuilder = $this->_em->createQueryBuilder('v');

	$queryBuilder
		->select('v.id','v.nomVis','v.prenomVis','v.loginVis')
		->from('GSBVisiteurBundle:Visiteur','v')
		->where('v.loginVis = :login')
		->setParameter('login',$login)
		->andwhere('v.mdpVis = :mdp')
		->setParameter('mdp', $mdp);
	return $queryBuilder->getQuery()->getArrayResult();
	}

	public function leVisiteur($id){
	$queryBuilder = $this->_em->createQueryBuilder('v');

	$queryBuilder
		->select('v')
		->from('GSBVisiteurBundle:Visiteur','v')
		->where('v.id = :id')
		->setParameter('id',$id);

	return $queryBuilder->getQuery()->getSingleResult();
	}
    
	
   
}
