<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (!class_exists(\ContainerCaiullk\appDevDebugProjectContainer::class, false)) {
    require __DIR__.'/ContainerCaiullk/appDevDebugProjectContainer.php';
}

if (!class_exists(appDevDebugProjectContainer::class, false)) {
    class_alias(\ContainerCaiullk\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerCaiullk\appDevDebugProjectContainer();
